Repository WeMake-AI/.github, pull requests merged in 2025-09, with the labels that each got.

#1 docs: fix relative paths in profile README links
  profile/README.md
Labels: documentation

#8 Interne Links aktualisiert; neues Review- und Commit-Check-Setup
  .coderabbit.yaml
  .commitlintrc.yaml
  .husky/pre-commit
  .prettierignore
  bun.lock
  package.json
  profile/README.md
  profile/handbuch/01.md
  profile/handbuch/02.md
  profile/handbuch/03.md
  profile/handbuch/04.md
  profile/handbuch/05.md
  profile/handbuch/06.md
  profile/handbuch/07.md
  profile/handbuch/08.md
  profile/handbuch/09.md
  profile/handbuch/10.md
  profile/handbuch/11.md
  profile/handbuch/12.md
  profile/handbuch/13.md
  profile/handbuch/14.md
  profile/handbuch/15.md
Labels: documentation, KI-Strategie, Knowledge Base, Chore, Prozess

#11 English translation
  profile/README-DE.md
  profile/README-de.md
  profile/README.md
Labels: documentation, Knowledge Base
